### ISSUE TITLE
Menu create view 관련

### ISSUE THREAD

**Issue by nxxxtyetdecided** [wanted-pre-onboarding-2nd-BE-Team-D/002_Bear_Robotics_Korea#15]
![image](https://user-images.githubusercontent.com/86827063/166405087-4c8e8521-e2b9-41c8-a306-1ed678b5bb12.png)
**이렇게 subdiary가 있을 때**

**/restaurant/subsidary/menu 에서**
![image](https://user-images.githubusercontent.com/86827063/166406112-fd4b099b-eab6-4e6c-9431-0c90fbba0233.png)
`
{
 "subsidary": 2,
 "name": "메뉴1",
 "price": 12000
}
`

![image](https://user-images.githubusercontent.com/86827063/166405199-6ddfadcf-de41-4703-88fb-3aaf020ec5ce.png)
이렇게 201 이 돌아오는 것 까지 확인을 했는데
model에 저장이 되지 않습니다.

제가 알기론
serializer.save를 하면 serializer에 들어온 값들이 model로 저장된다고 알고 있는데 
` if serializer.is_valid():`
`serializer.save(subsidary=subsidary)`
 `return Response(serializer.data, status=status.HTTP_201_CREATED)`
제가 놓친 부분이 있다면 말씀해주세요!

**Comment by rsh1994** [comment]
첫번째 사진에서 쉽표가 하나 없는것은 문제가 없을까요 !?

**Comment by nxxxtyetdecided** [comment]
~~~
    def post(self, request):
        serializer = MenuSerializer(data=request.data) # 이부분에 subdiary가 중복으로 들어가 생긴 문제였음
        if serializer.is_valid(raise_exception=True):
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
~~~

MenuSerializer에 subsidiary를 없애니 잘 생성이 됩니다!
request에도 subsidary가 있는데 추가적으로 넣어 생긴 문제 같습니다.
